// Code generated by mockery. DO NOT EDIT.

package urlshortener

import (
	context "context"

	entity "github.com/arfan21/backend-test/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, shortURL
func (_m *Repository) Get(ctx context.Context, shortURL string) (entity.URLShortener, error) {
	ret := _m.Called(ctx, shortURL)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.URLShortener
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.URLShortener, error)); ok {
		return rf(ctx, shortURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.URLShortener); ok {
		r0 = rf(ctx, shortURL)
	} else {
		r0 = ret.Get(0).(entity.URLShortener)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - shortURL string
func (_e *Repository_Expecter) Get(ctx interface{}, shortURL interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, shortURL)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, shortURL string)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(res entity.URLShortener, err error) *Repository_Get_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(context.Context, string) (entity.URLShortener, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, value
func (_m *Repository) Set(ctx context.Context, value entity.URLShortener) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.URLShortener) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Repository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - value entity.URLShortener
func (_e *Repository_Expecter) Set(ctx interface{}, value interface{}) *Repository_Set_Call {
	return &Repository_Set_Call{Call: _e.mock.On("Set", ctx, value)}
}

func (_c *Repository_Set_Call) Run(run func(ctx context.Context, value entity.URLShortener)) *Repository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.URLShortener))
	})
	return _c
}

func (_c *Repository_Set_Call) Return(err error) *Repository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Set_Call) RunAndReturn(run func(context.Context, entity.URLShortener) error) *Repository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
